/**
 * app/layout.tsx — PodLever root layout
 *
 * Part of: PodLever
 * Created: 2026-07-18
 * Last modified: 2026-07-19 by agent (Task #13 — Full SEO metadata, OG tags)
 *
 * HUMAN REVIEW NOTES:
 * Auth in PodLever uses iron-session (encrypted HTTP-only cookies) — no client-side
 * AuthProvider React Context is needed. Auth state is read server-side via getAuthUser()
 * in each Server Component that needs it (e.g., app/page.tsx).
 *
 * SEO strategy:
 *   - Root metadata provides sitewide defaults (title template, OG base).
 *   - Individual pages override via their own `export const metadata` or
 *     `generateMetadata()` export as needed.
 *   - OG image is generated by app/opengraph-image.tsx (Next.js image route).
 *   - Twitter card mirrors OG tags for cross-platform sharing.
 */

import type { Metadata, Viewport } from "next";
import "./globals.css";

// ─── Production URL ───────────────────────────────────────────────────────────

/**
 * SITE_URL — The canonical base URL for the site.
 *
 * Reads NEXT_PUBLIC_SITE_URL (set in .env.production or Replit Secrets).
 * Falls back to the dev domain in development.
 * Used for sitemap, canonical URLs, and absolute OG image URLs.
 */
const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.REPLIT_DEV_DOMAIN
    ? `https://${process.env.REPLIT_DEV_DOMAIN}`
    : "https://podlever.replit.app");

// ─── Root metadata ────────────────────────────────────────────────────────────

/**
 * metadata — Sitewide SEO defaults.
 *
 * Individual pages can override title, description, and alternates.canonical
 * by exporting their own `metadata` object.
 */
export const metadata: Metadata = {
  // Title template: page-specific titles appear as "Page — PodLever"
  title: {
    default:  "PodLever — Podcast Content Engine",
    template: "%s — PodLever",
  },

  description:
    "One recording. A complete content library. PodLever transforms your raw podcast episode into transcript, show notes, blog post, social clips, and guest media pack — automatically.",

  // Robots
  robots: {
    index:  true,
    follow: true,
    googleBot: { index: true, follow: true },
  },

  // Canonical URL base (pages override alternates.canonical)
  metadataBase: new URL(SITE_URL),

  // Open Graph
  openGraph: {
    type:        "website",
    siteName:    "PodLever",
    title:       "PodLever — Podcast Content Engine",
    description:
      "One recording. A complete content library. Transcript, show notes, blog post, social clips, and guest media pack — automatically.",
    url:         SITE_URL,
    images: [
      {
        url:    "/opengraph-image",
        width:  1200,
        height: 630,
        alt:    "PodLever — One recording. A complete content library.",
      },
    ],
  },

  // Twitter / X Card
  twitter: {
    card:        "summary_large_image",
    title:       "PodLever — Podcast Content Engine",
    description:
      "One recording. A complete content library. PodLever automates your podcast post-production.",
    images:      ["/opengraph-image"],
    creator:     "@russellnomer",
  },

  // App info (used by some crawlers/platforms)
  applicationName: "PodLever",
  authors:         [{ name: "Russell Nomer", url: "https://www.linkedin.com/in/russellnomer/" }],
  creator:         "Russell Nomer",
  publisher:       "Russell Nomer Consulting",

  // Structured data hints (full JSON-LD injected in RootLayout below)
  category: "Technology",
};

// ─── Viewport ─────────────────────────────────────────────────────────────────

export const viewport: Viewport = {
  themeColor:   "#0D0D0F",
  width:        "device-width",
  initialScale: 1,
};

// ─── JSON-LD structured data (module scope) ───────────────────────────────────

/**
 * JSON_LD — SoftwareApplication schema for Google rich results.
 *
 * Defined at module scope (not inside the component) so it is evaluated once
 * at build time and never re-computed per render. A per-render definition
 * creates a new object reference on every hydration, which can trigger subtle
 * mismatches if the value ever becomes dynamic.
 *
 * suppressHydrationWarning is added to the <script> tag below so React does
 * not throw when a browser extension (ad blocker, SEO tool, password manager)
 * touches the `type` attribute after the server HTML is delivered. This is the
 * officially recommended pattern for inline JSON-LD script tags in React apps.
 */
const JSON_LD = {
  "@context": "https://schema.org",
  "@type":    "SoftwareApplication",
  name:       "PodLever",
  description:
    "PodLever transforms raw podcast episodes into a complete content suite: transcript, show notes, blog post, social clips, and guest media pack.",
  url:          SITE_URL,
  applicationCategory: "MultimediaApplication",
  operatingSystem:     "Web",
  offers: {
    "@type":       "AggregateOffer",
    priceCurrency: "USD",
    lowPrice:      "0",
    highPrice:     "97",
    offerCount:    "3",
  },
  author: {
    "@type": "Person",
    name:    "Russell Nomer",
    url:     "https://www.linkedin.com/in/russellnomer/",
  },
  publisher: {
    "@type": "Organization",
    name:    "Russell Nomer Consulting",
  },
};

// ─── Root layout ──────────────────────────────────────────────────────────────

/**
 * RootLayout — the root Next.js layout.
 *
 * Injects JSON-LD structured data (SoftwareApplication schema) for Google
 * rich results. The schema is static — no runtime data needed.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* JSON-LD structured data — suppressHydrationWarning prevents React
            from throwing when browser extensions modify the type attribute. */}
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
          suppressHydrationWarning
        />
      </head>
      <body className="antialiased bg-[#0D0D0F] text-zinc-100">
        {children}
      </body>
    </html>
  );
}
