/**
 * db/schema/business-costs.ts — Fixed monthly business costs ledger
 *
 * Part of: PodLever
 * Created: 2026-07-27 by agent (founder request — full cost picture on /admin/cogs)
 *
 * Stores recurring fixed costs the founder enters once (Replit hosting,
 * GoDaddy domain, Google Workspace, Viktor, etc.) so /admin/cogs can show
 * true monthly burn and margin — not just per-episode AI COGS.
 *
 * Design choices:
 *   - monthly_usd is the normalized monthly amount (annual bills ÷ 12)
 *   - `active` soft-delete keeps historical context without losing rows
 *   - No FK dependencies; owner-managed via /admin/cogs
 *
 * Access:
 *   - Written by business-costs server actions (owner-only)
 *   - Read by /admin/cogs (owner-only)
 */

import { pgTable, text, timestamp, uuid, numeric, boolean } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/** Cost categories for grouping in the admin view. */
export const COST_CATEGORIES = ["infrastructure", "software", "services", "other"] as const;
export type CostCategory = (typeof COST_CATEGORIES)[number];

export const businessCosts = pgTable("business_costs", {
  /** UUID primary key — generated by Postgres */
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),

  /** Human label, e.g. "Replit Core + Autoscale", "GoDaddy podlever.com" */
  label: text("label").notNull(),

  /** Grouping category: infrastructure | software | services | other */
  category: text("category").notNull().default("infrastructure"),

  /** Normalized monthly amount in USD (enter annual bills ÷ 12) */
  monthlyUsd: numeric("monthly_usd", { precision: 10, scale: 2 }).notNull(),

  /** Optional note, e.g. "annual bill $228, renews Mar 2027" */
  notes: text("notes"),

  /** Soft delete — inactive rows are excluded from burn totals */
  active: boolean("active").notNull().default(true),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
});

export type BusinessCost    = typeof businessCosts.$inferSelect;
export type NewBusinessCost = typeof businessCosts.$inferInsert;
