/**
 * db/schema/feedback.ts — In-app feedback submissions
 *
 * Part of: PodLever
 * Created: 2026-07-21 by agent
 *
 * Stores bug reports and feedback from beta testers collected via the in-app
 * FeedbackWidget. Each row is append-only; no UPDATE or DELETE is expected.
 *
 * Design choices:
 *   - userId stored as text (not FK) so rows survive user deletion
 *   - displayName denormalised at write time for readable admin queries
 *   - pageUrl captured automatically so every report has context
 *
 * Access:
 *   - Written by submitFeedbackAction (any active beta user or owner)
 *   - Read by the owner at /admin/feedback (future admin page)
 */

import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { sql }                            from "drizzle-orm";

export const feedback = pgTable("feedback", {
  /** UUID primary key — generated by Postgres */
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),

  /**
   * DB user ID of the submitter.
   * Stored as text (not FK) so rows are not orphaned if the user is deleted.
   */
  userId: text("user_id").notNull(),

  /** Display name at time of submission — readable without a JOIN */
  displayName: text("display_name").notNull(),

  /**
   * Full URL of the page where the widget was open.
   * Captured automatically by the client so every report has context.
   */
  pageUrl: text("page_url").notNull(),

  /** Free-text feedback body (max 2000 chars enforced in the server action) */
  message: text("message").notNull(),

  /** Submission timestamp */
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),

  // ── Knowledge-base fields (added 2026-07-27, founder request) ──────────────
  // The inbox doubles as a problem→solution record: each item is triaged to a
  // status, and resolved items link to the GitHub PR/issue that fixed them.

  /** Triage status: 'new' | 'in_progress' | 'addressed' | 'wont_fix' */
  status: text("status").notNull().default("new"),

  /** Owner's note describing how the feedback was addressed */
  resolutionNote: text("resolution_note"),

  /** Link to the GitHub PR/issue/commit that resolved it */
  resolutionLink: text("resolution_link"),

  /** When the item was marked addressed/wont_fix */
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
});

/** Valid feedback triage statuses. */
export const FEEDBACK_STATUSES = ["new", "in_progress", "addressed", "wont_fix"] as const;
export type FeedbackStatus = (typeof FEEDBACK_STATUSES)[number];

export type Feedback    = typeof feedback.$inferSelect;
export type NewFeedback = typeof feedback.$inferInsert;
