kind = "web"
previewPath = "/"
title = "PodLever"
version = "1.0.0"
id = "podlever-nextjs-app"

[[services]]
localPort = 3000
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/podlever run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/podlever", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/podlever", "run", "start"]

[services.production.run.env]
PORT = "3000"
NODE_ENV = "production"

[services.production.health.startup]
path = "/"
